name: CI/CD Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run lint test
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Run e2e tests
        run: npx start-server-and-test start http://localhost:3000 test:e2e

      - name: Build the app
        run: npm run build

      - name: Push to deploy branch
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com" 
          git config --global user.name "GitHub Actions"
          git fetch origin deploy:deploy || true
          git checkout deploy || git checkout -b deploy
          git reset --hard origin/master
          git push --force origin deploy
        env:
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: GitHub Actions
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
