name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Adjust this to match your main branch name
  pull_request:
    branches:
      - main # Adjust this to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Lint Test
        run: npm run lint

      - name: Unit Tests
        run: npm run test:unit

      - name: Build App
        if: success() # Only run if previous steps succeed
        run: npm run build
